import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Poppins} from "next/font/google";
import Header from "@/components/Header";

const poppins = Poppins({
  subsets:["latin"],
  weight: ["400","700"]
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
